const predefinedMessages = [
  "Hey guys, anyone started the Play 3 Games for 5 minutes offer?",
  "Yeah I did, it’s working fine so far!",
  "Hello everyone! Just joined the group 😊",
  "Bro I just finished the Just Play 2 games for 10 minutes each and got my reward!",
  "OMG I finally got my reward after Helium Mobile Zero Plan subscription!",
  "Does the TikTok 30 seconds step really count?",
  "Yep, just open it for 30 seconds and it triggers instantly.",
  "Hi all, anyone stuck on the last game?",
  "I was stuck too, but then completed it fully and reward appeared.",
  "Huge thanks to this site, I did Play 3 Games for 5 minutes each and boom reward!",
  "Hey, is this safe on iPhone?",
  "Yes bro, I just finished it on iPhone and it worked.",
  "Guys, do I need to scroll in the apps or just open them?",
  "Tap around a little, that’s what made mine track.",
  "Just did the Helium Mobile step, waiting for reward…",
  "Mine came in like 3 minutes, it’s normal.",
  "Hello everyone! Can someone guide me on the Just Play steps?",
  "Sure, play both games for 10 minutes each, that’s what worked for me.",
  "OMG my reward just popped after TikTok step!",
  "Bro same! I was shocked it worked so fast.",
  "Hi, anyone from Europe got their reward?",
  "Yeah I’m from Germany and it worked fine.",
  "I’m nervous the last step won’t work.",
  "Relax bro, mine showed up right after completing everything.",
  "Just finished Play 3 Games offer, fingers crossed!",
  "You got this! It should appear soon.",
  "Thanks guys, TikTok step really worked!",
  "No problem, glad it helped!",
  "Hello all! I completed Helium Mobile Zero Plan and reward showed instantly!",
  "Same here, site is actually legit.",
  "Bro, Just Play games took forever for me.",
  "Yeah but reward came right after, totally worth it.",
  "OMG finally, my reward after 3 games!",
  "Congrats! That’s the best feeling ever.",
  "Anyone else confused about Helium Mobile step?",
  "Just subscribe to Zero Plan, it counts immediately.",
  "Hi guys, just did TikTok 30s, waiting…",
  "Mine came in 2 minutes, don’t stress.",
  "I’m so happy, finally got my reward!",
  "Yesss! That feeling is crazy.",
  "Hey, do the steps work outside US?",
  "I’m not in the US and it worked perfectly.",
  "Guys, almost gave up on last step!",
  "Don’t quit, just complete fully and reward pops.",
  "Just finished all offers, hope reward comes soon!",
  "It will! Be patient, mine came in a few minutes.",
  "Hello, Play 3 Games step counted for me perfectly!",
  "Nice! Glad it worked for you.",
  "OMG I got my reward after Just Play 10-minute games!",
  "Bro same here, it actually works.",
  "Hi all, TikTok 30s was my final step, got it instantly!",
  "Congrats bro! Enjoy your reward.",
  "Hey, how long did Helium Mobile take for you?",
  "Super fast, subscribed and reward came in minutes.",
  "Guys, I feel like Play 3 Games is easy but important.",
  "Yeah, it’s the first one that counts the steps correctly.",
  "OMG just received my reward after Helium!",
  "Bro congrats! That’s legit amazing.",
  "Hello everyone, Just Play worked for me too.",
  "Yup, step tracking is flawless.",
  "Hi guys, TikTok step triggered my reward instantly!",
  "Wow nice! I’m happy for you.",
  "Anyone else feel nervous before last step?",
  "Same bro, but patience pays off.",
  "Finally did Play 3 Games, waiting now…",
  "It will show, trust the process.",
  "Thanks site, Just Play games worked like magic!",
  "No problem, enjoy your reward!",
  "OMG reward popped right after TikTok!",
  "Bro same, legit site.",
  "Hey all, Helium Mobile counted in 1 minute.",
  "Nice! That’s super fast.",
  "Hello, completed Play 3 Games and reward came in 3 mins!",
  "Congrats, enjoy it man.",
  "Hey, anyone stuck on Just Play 2 games?",
  "Play full 10 mins each, it will count.",
  "OMG finally got reward from TikTok step!",
  "Congrats! That’s crazy fast.",
  "Hi, Helium Mobile worked perfectly for me!",
  "Same bro, literally instant reward.",
  "Guys, last step is TikTok 30s for me.",
  "Do it fully, reward will show.",
  "Hello, completed all offers and got my reward!",
  "Yesss! That’s the feeling we wanted.",
  "OMG Play 3 Games reward popped up!",
  "Bro congrats! Enjoy it.",
  "Hi, TikTok step worked perfectly for me.",
  "Same here, site legit.",
  "Anyone else completing Just Play games?",
  "Yeah, reward popped right after I finished both.",
  "OMG Helium Mobile counted instantly!",
  "Bro amazing, that step is so easy.",
  "Hi guys, Play 3 Games worked for me!",
  "Congrats, that’s the fastest reward.",
  "Hello all, finally TikTok step triggered mine.",
  "Bro same, instant reward.",
  "Hey, Just Play worked perfectly after 10 mins each.",
  "Yes! That’s what counts the most.",
  "OMG Play 3 Games reward just popped!",
  "Bro congrats, so hyped!",
  "Hello, TikTok 30s step done, reward received!",
  "Nice one, site is actually legit.",
  "Hi guys, Helium Mobile subscription worked like a charm.",
  "Bro same here, instantly got my reward.",
  "OMG Just Play 2 games for 10 mins counted perfectly!",
  "Congrats! Feeling great right?",
  "Hello everyone, completed Play 3 Games and reward popped up.",
  "Yesss bro, feeling like a winner.",
  "Hi, TikTok step worked like a charm!",
  "Bro congrats, enjoy the reward!",
  "OMG Helium Mobile Zero Plan counted instantly!",
  "That’s crazy fast, love it!",
  "Hey all, Just Play 10-minute games finally unlocked my reward.",
  "Nice man, enjoy it!",
  "Hello, Play 3 Games for 5 mins each step worked perfectly.",
  "Bro congrats, site legit af!",
  "Hi guys, TikTok 30s finally triggered mine.",
  "Yeah bro, so happy it worked!",

  "Finally completed all steps, hoping the reward comes soon.",
  "It will! Mine came when I least expected it.",
  "Anyone having trouble with the second game on Just Play?",
  "I had issues but once I actually played for 10 minutes, it counted.",
  "I just got my reward after doing the TikTok step, this is insane.",
  "Dude this really works, I’m shocked.",
  "Do we have to keep apps open after finishing them?",
  "Nope, once they count the action, you're good.",
  "I'm on the Helium Mobile step now, wish me luck.",
  "Good luck bro, it's an easy one.",
  "Wooo! Reward received!!!",
  "Same here, the excitement is real.",
  "How long does the Play 3 Games offer take overall?",
  "Around 15 minutes total for me.",
  "Guys I think I'm stuck at the last offer.",
  "Finish the requirement fully, it unlocks after the last step.",
  "Just got mine too!!",
  "Congrats! Enjoy it!",
  "Anyone else doing this at work? 😂",
  "Bro I'm literally in the bathroom doing this rn.",
  "I swear the last step is always the important one.",
  "Facts, completing the final app is what triggers the reward.",
  "Is it normal if nothing shows up after finishing?",
  "Yes bro, just give it a bit, mine took 3–5 minutes.",
  "I’m getting so close, last app loading.",
  "You got this, finish it and wait.",
  "THIS IS LEGIT OMG 😭",
  "Told y'all it’s real.",
  "Is the TikTok 30 seconds step easy?",
  "Super easy, just open and wait.",
  "Anyone else feeling hyped rn?",
  "Bro I'm smiling like an idiot after getting mine.",
  "I completed all steps and my reward appeared while I wasn’t looking lol.",
  "That's what happened to me! It just popped suddenly.",
  "Ok I just subscribed to Helium Zero Plan… now waiting.",
  "It should show soon, mine appeared fast.",
  "I'm so glad this group exists omg.",
  "Same bro, everyone helps each other.",
  "Damn, I really got rewarded… crazy.",
  "Yesssirrr! Enjoy it bro.",
  "How long did the Just Play one take for you guys?",
  "About 10 minutes, but it worked smoothly.",
  "Anyone else doing multiple offers at once?",
  "Nah do them one at a time so it tracks right.",
  "Finally done! Waiting for the magic to happen.",
  "Keep your screen on for a bit, it usually pops.",
  "Omg it just popped up!! LET'S GOOO",
  "HAHA congrats bro!",
  "This is like the only system that actually gives rewards.",
  "Real talk, this is the best one so far.",
  "Anyone from Europe here? Did it work?",
  "I'm from Germany and yes, it worked fine.",
  "What about the Play 3 Games step—do they all count instantly?",
  "Yes, as long as you play each for 5 minutes.",
  "Holy crap I just received my reward.",
  "Bro same!! This is wild.",
  "Guys is it normal to replay a game if it doesn't track?",
  "Yeah, I replayed and it tracked the second time.",
  "Question: does the app need to stay open?",
  "Only while completing the task, after that you're good.",
  "MY REWARD JUST ARRIVED 😭🔥",
  "Let’s goooo!!",
  "I think the TikTok one is the easiest fr.",
  "Facts bro, super quick.",
  "Anyone still waiting more than 5 mins?",
  "Mine came at 6 mins, don’t stress.",
  "Damn I’m actually happy rn 😂",
  "Same bro, feels good when it works.",
  "Guys I’m starting now, wish me luck 🫡",
  "You got this bro, complete the steps!",
  "HELLOOO I JUST GOT MY REWARD LETS GOOOO 🔥🔥",
  "GG!! Welcome to the winners club 😂",
  "Do you guys keep refreshing or nah?",
  "I didn’t, it appeared on its own.",
  "Almost done with my final game!",
  "Stay strong bro, you're close!",
  "Just finished the Helium task… waiting now.",
  "It’ll come, mine appeared soon after.",
  "BROOO IT ARRIVED!!!",
  "LET’S GOOOOO man congrats!",
  "This group is pure motivation lol.",
  "For real, everyone helps each other here.",
  "FINALLY MY REWARD POPPED UP OMG.",
  "Yessss bro enjoy it!!!"
];

